### ISSUE TITLE
Driver inconsistency with X4

### ISSUE THREAD

**Issue by RodrigoCatto** [YDLIDAR/ydlidar_ros_driver#4]
I was trying to run my X4 with slam_toolbox, but when I launched slam_toolbox I kept receiving an error message stating:

`LaserRangeScan contains 719 range readings, expected 729`

Here is the header of the /scan topic:
```
header: 
  seq: 4289
  stamp: 
    secs: 1631644371
    nsecs: 564544000
  frame_id: "base_scan"
angle_min: -3.14159274101
angle_max: 3.14159274101
angle_increment: 0.00869043637067
time_increment: 0.000199999994948
scan_time: 0.130799993873
range_min: 0.10000000149
range_max: 12.0
```

I tried with the older package from YDLIDAR/ydlidar_ros and it worked just fine... I realize that **angle_increment** was a little different:
```
header: 
  seq: 128
  stamp: 
    secs: 1631645675
    nsecs: 389754000
  frame_id: "laser_frame"
angle_min: -3.14159274101
angle_max: 3.14159274101
angle_increment: 0.00873878411949
time_increment: 0.000200000009499
scan_time: 0.130600005388
range_min: 0.10000000149
range_max: 12.0
```

Do you have any clue why there is this difference?
